### ISSUE TITLE
Is it possible to build the PlubApp without PlusBuild?

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusApp#24]
I am trying to build PlusApp linking to precompiled libraries instead of the PlusBuild ones.  I have two doubts:

1. Why does cmake request about VTK_DIR, ITK_DIR, OpenIGTLinkIO_DIR, and OpenCV_DIR? when I set up the path for the OpenIGTLinkIO_DIR, the cmake warns that the variables were already defined. This is the error message I get: 
`CMake Error at ···· openIGTlinkIO/lib/cmake/igtlio/OpenIGTLinkIOTargets.cmake:34 (message):
Some (but not all) targets in this export set were already defined.
  Targets Defined: igtlioConverter;igtlioDevices;igtlioLogic
  Targets not yet defined: igtlioTools`
2. Why do I need to link these libraries to PlusApp, when PlusLib already does it?

I appreciate some guidances.

**Comment by lassoan** [comment]
Of course it is possible to build PlusApp without PlusBuild, but you then have to do all the build steps manually (checkout and build required libraries and configure PlusApp to find them). If you have any doubts what PlusApp needs, just build using PlusBuild first and see what it builds. You can find in External_PlusApp.cmake all the information that are passed to the PlusApp build.

**Comment by adamrankin** [comment]
I will try to build openigtlinkio to make sure the cmake logic is correctly done for out-of-tree builds

**Comment by adamrankin** [comment]
PlusBuild CMake uses the _DIR variables as the location of the build folders for the various libraries. If you want to use PlusBuild to build some libraries, but use some of your own, then you could set (for example) VTK_DIR to use your own VTK, but have PlusBuild build everything else (it will pass your VTK to all the other projects as well).

**Comment by carlos-luque** [comment]
Thanks a lot for your answers.

Unfortunately, I have already tried these solutions. I set up the _DIR variables in the PlusApp Cmake. These variables are VTK_DIR, ITK_DIR and PlusLib_DIR and they reference to successfully compiled libraries (VTK, ITK, and PlusLib).
Cmake warns the following messages:

`CMake Warning at CPackConfig.cmake:105 (MESSAGE):
  Unable to set OpenIGTLinkIO_DIR for package generation!
Call Stack (most recent call first):
  CMakeLists.txt:196 (INCLUDE)`

`CMake Warning at CPackConfig.cmake:115 (MESSAGE):
  Unable to set OpenCV_DIR for package generation!
Call Stack (most recent call first):
  CMakeLists.txt:196 (INCLUDE)`

When I run the command line _make_, I have the following error:

`/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.h:17:10: fatal error: igtlioLogic.h: No existe el archivo o el directorio
 #include <igtlioLogic.h>
compilation terminated.
`

If I set up the variable OpenIGTLinkIO_DIR in PlusApp CMake, the cmake shows the message:

`CMake Error at ···· openIGTlinkIO/lib/cmake/igtlio/OpenIGTLinkIOTargets.cmake:34 (message): Some (but not all) targets in this export set were already defined. Targets Defined: igtlioConverter;igtlioDevices;igtlioLogic Targets not yet defined: igtlioTools` 

I am working on it. Any suggestion will be welcome.

**Comment by adamrankin** [comment]
Linux?

**Comment by carlos-luque** [comment]
Yes, I am working in Linux.

**Comment by carlos-luque** [comment]
No, I didn't. I have compiled PlusLib succesfully. Now I am trying to compile **_PlusApp_** and cmake asks not only PlusLib (PlusLib_DIR), but also VTK_DIR, ITK_DIR, and so on.

**Comment by adamrankin** [comment]
(OpenIGTLinkIO_DIR is required transitively, but should be transparent if PlusLib is configured/built as we think it should be).

**Comment by carlos-luque** [comment]
This is the file. The dummy extension txt is due to supported files. 
 
[PlusLibConfig .cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1363009/PlusLibConfig.cmake.txt)

**Comment by adamrankin** [comment]
and in PlusApp, you have no manually set an OpenIGTLinkIO_DIR, correct?

Could you upload OpenIGTLinkIOConfig.cmake from 
`/opt/home/cluque/local/software/openIGTlinkIO/lib/cmake/igtlio`
or the directory you've specified in OpenIGTLinkIO_DIR (if applicable)

**Comment by carlos-luque** [comment]
I manually set up OpenIGTLinkIO_DIR. 

[OpenIGTLinkIOConfig.cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1363032/OpenIGTLinkIOConfig.cmake.txt)

**Comment by adamrankin** [comment]
Ok, PlusLib should be responsible for managing OpenIGTLinkIO_DIR.

Could you remove the override from PlusApp?

Also, are any of the libraries installed via a package manager? Or are all dependencies built?

**Comment by carlos-luque** [comment]
I built all dependencies. 

If I remove OpenIGTLinkIO_DIR from PlusApp Cmake, then I get the warning
`CMake Warning at CPackConfig.cmake:105 (MESSAGE): Unable to set OpenIGTLinkIO_DIR for package generation! Call Stack (most recent call first): CMakeLists.txt:196 (INCLUDE)`

**Comment by adamrankin** [comment]
Does the folder
`/opt/home/cluque/local/software/openIGTlinkIO/lib/cmake/igtlio`
exist?

**Comment by carlos-luque** [comment]
Finally, I could build the PlusApp, because I switched the folder _-prefix_ to the folder _-bin_.  The issue was that the variables _OpenIGTLinkIO_DIR_ and _OpenCV_DIR_ in PlusLib had not be set up correctly. 

I cannot understand why the PLusApp requests the VTK and ITK libraries if they are defined by PlusLib.

**Comment by adamrankin** [comment]
They don't. They call FindPackage(PlusLib) which in turn establishes all of its dependencies in PlusLibConfig.cmake

**Comment by carlos-luque** [comment]
I have checked it in the file PlusLibConfig.cmake (attached). I think that the variables are properly defined. 
[PlusLibConfig.cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1369049/PlusLibConfig.cmake.txt)

Do you think it is correct configuration?

**Comment by adamrankin** [comment]
It's autogenerated based on the inputs you give PlusLib. If you're able to build PlusLib, then you should be able to build PlusApp.

**Comment by adamrankin** [comment]
I believe if you had given a -prefix dir to PlusLib, it would not have built.

**Comment by carlos-luque** [comment]
Finally, both libraries (PlusApp and PlusLib) were built. I can execute fcal, PlusServerLauncher, and  DiagnosticTool. 

Thanks for your time.

**Comment by adamrankin** [comment]
No problem, sorry it didn't go smoothly. I admit we rarely have people build the supporting libraries independently.

**Comment by Sunderlandkyl** [comment]
This issue was moved to PlusToolkit/PlusLib#230
