### ISSUE TITLE
Move PlusApp Issues to PlusLib

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusApp#31]
Currently, issues are spread between PlusLib, PlusApp, and PlusBuild repositories.

For clarity, all issues are being moved to PlusLib and issue tracking is being disabled on PlusApp and PlusBuild.

**Comment by Sunderlandkyl** [comment]
This tool seems useful for this task: https://github.com/google/github-issue-mover

@lassoan Any reason to not begin migrating the issues right now?

**Comment by lassoan** [comment]
The sooner the better.

**Comment by Sunderlandkyl** [comment]
Done!
